
---
- hosts: javaserver
  become: yes
  tasks:
    - name : i want to install open jdk 8 on ubuntu server
      apt:
         name: "{{myubuntujavapackage}}"
         state: present
      when: ansible_os_family == "Debian"

    - name: i want to install open jdk 8 on redhat server
      yum:
         name: "{{myredhatjavapacakge}}" 
         state: present
      when: ansible_os_family == "RedHat"
