---
- hosts: javaserver
  become: yes
  tasks: 
    - name : i want to run linux command
      command: hostname -f
      register: myresult
s
    - name : i want to display linux command output value
      debug:
         msg: "{{myresult}}"

    - name: i want to intall git
      apt: 
         name: git
         state: present
      when: myresult.stderr != ""

    - name: i want to install tree
      apt:
         name : tree
         state: present
      when: myresult.stderr == ""