---
- hosts: javaserver
  become: yes
  vars:
    myvar1 : git
    myvar2 : tree
    myvar3 : apache2
  tasks:
      - name: i want display variable variable
        debug: 
          msg : "{{myvar3}}"

      - name: i want to install git
        apt:
            name: "{{item}}"
            state: present
        loop: 
         - "{{myvar1}}"
         - "{{myvar2}}"
         - "{{myvar3}}"