---
- hosts: all
  become: yes
  tasks:

      - name: install tree
        apt:
           name: tree
           state: present

      - name: install nginx
        apt:
           name: nginx
           state: present
           
       - name: install apache2
        apt:
           name: apache2
           state: present