---
- hosts: all
  become: yes
  tasks:
      - name: install tree
        apt:
           name: tree
           state: present
      - name: install nginx
        apt:
           name: nginxg
           state: present